apiVersion: v1
kind: Secret
metadata:
  name: collabdocs-secrets
  namespace: collabdocs
type: Opaque
stringData:
  MONGO_URI: "your_mongodb_uri"
  JWT_SECRET: "your_jwt_secret_min_32_chars"
  JWT_REFRESH_SECRET: "your_refresh_secret_min_32_chars"
  CLIENT_URL: "https://your-frontend-domain.com"
  GMAIL_USER: "your@gmail.com"
  GMAIL_PASS: "your_app_password"
  EMAIL_FROM: "CollabDocs <noreply@yourdomain.com>"
